const ably = {
  title: "홈투데이",
  screen_name: "TODAY",
  view_event_logging: {},
  logging: {
    SCREEN: "TODAY",
  },
  components: [
    {
      component_id: 128,
      type: {
        header: null,
        item_list: "TWO_COL_CARD_LIST",
        footer: null,
      },
      logging: {
        analytics: {
          LIST_ID: "today_recommend",
        },
        inhouse: {
          list_id: "today_recommend",
        },
      },
      entity: {
        header: null,
        item_list: [
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 31344800,
                name: "핫딜🔥[밑단스냅🤎/도톰융기모][140cm~/1+1할인/투웨이/겨울신상] 제이닝 140/150/160 기장선택 밍크 코듀로이 와이드 팬츠 겨울 골덴 교복 바지 당일",
                market_sno: 4444,
                market_name: "제이닝",
                image: "https://d3ha2047wt6x28.cloudfront.net/4NjMBZDNqVs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzlkMmRiNDcxMDMzNWI4ZjIzNmI0YTFlNGE3YTYyMDZiLmdpZg",
                closed_reason: null,
                sell_count: 8775,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "핫딜🔥[밑단스냅🤎/도톰융기모][140cm~/1+1할인/투웨이/겨울신상] 제이닝 140/150/160 기장선택 밍크 코듀로이 와이드 팬츠 겨울 골덴 교복 바지 당일",
                  market_name: "제이닝",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/I9lycAEiMKY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk1MDY4MjYyNzE5NDJtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/qri8seOnUtc/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2Mjc4ODEzMzIzMzkzNDkuanBn",
                  discount_rate: 58,
                  original_price: 51500,
                  price: 21500,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 21500,
                discount_rate: 58,
                like: {
                  goods_sno: 31344800,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 3,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/31344800/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "셀럽",
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/31344800/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5Cud56b%5Cub51c%5Cud83d%5Cudd25%5B%5Cubc11%5Cub2e8%5Cuc2a4%5Cub0c5%5Cud83e%5Cudd0e%2F%5Cub3c4%5Cud1b0%5Cuc735%5Cuae30%5Cubaa8%5D%5B140cm~%2F1%2B1%5Cud560%5Cuc778%2F%5Cud22c%5Cuc6e8%5Cuc774%2F%5Cuaca8%5Cuc6b8%5Cuc2e0%5Cuc0c1%5D%20%5Cuc81c%5Cuc774%5Cub2dd%20140%2F150%2F160%20%5Cuae30%5Cuc7a5%5Cuc120%5Cud0dd%20%5Cubc0d%5Cud06c%20%5Cucf54%5Cub4c0%5Cub85c%5Cuc774%20%5Cuc640%5Cuc774%5Cub4dc%20%5Cud32c%5Cuce20%20%5Cuaca8%5Cuc6b8%20%5Cuace8%5Cub374%20%5Cuad50%5Cubcf5%20%5Cubc14%5Cuc9c0%20%5Cub2f9%5Cuc77c%22%2C%20%22market_name%22%3A%20%22%5Cuc81c%5Cuc774%5Cub2dd%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FI9lycAEiMKY%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk1MDY4MjYyNzE5NDJtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2Fqri8seOnUtc%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2Mjc4ODEzMzIzMzkzNDkuanBn%22%2C%20%22discount_rate%22%3A%2058%2C%20%22original_price%22%3A%2051500%2C%20%22price%22%3A%2021500%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "31344800",
                  GOODS_NAME: "핫딜🔥[밑단스냅🤎/도톰융기모][140cm~/1+1할인/투웨이/겨울신상] 제이닝 140/150/160 기장선택 밍크 코듀로이 와이드 팬츠 겨울 골덴 교복 바지 당일",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "4444",
                  MARKET_NAME: "제이닝",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 58,
                  SALES_PRICE: 21500,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 163,
                  REVIEW_COUNT_RANGE: "151~200",
                  REVIEW_RATING: 94,
                  LIKES_COUNT: 21076,
                  LIKES_COUNT_RANGE: "21,051~21,100",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 3,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 31344800,
                  list_id: "today_recommend",
                  list_index: 3,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/4NjMBZDNqVs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzlkMmRiNDcxMDMzNWI4ZjIzNmI0YTFlNGE3YTYyMDZiLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "핫딜🔥[밑단스냅🤎/도톰융기모][140cm~/1+1할인/투웨이/겨울신상] 제이닝 140/150/160 기장선택 밍크 코듀로이 와이드 팬츠 겨울 골덴 교복 바지 당일",
                  price: "21,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "58%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "제이닝",
                  store_text: "제이닝",
                  nudging_text: "8,775개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 17663829,
                name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
                market_sno: 64739,
                market_name: "제이와이홀딩스",
                image: "https://d3ha2047wt6x28.cloudfront.net/038iy9jUgMA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzU1MWFmYjQyN2I5MzgyZjZlMzc0NWE1YjliMzQzYjdiLmdpZg",
                closed_reason: null,
                sell_count: 14020,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
                  market_name: null,
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/OlvDMHrqRzo/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDE4XzE3MjkyNDgwNjk0NTYyOTltLnBuZw",
                  market_image: null,
                  discount_rate: 3,
                  original_price: 29900,
                  price: 28800,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 28800,
                discount_rate: 3,
                like: {
                  goods_sno: 17663829,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 4,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/17663829/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "프리미엄 브랜드",
                category_name: "플리스",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/17663829/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5Cuc815%5Cud488%5Cubcf4%5Cuc7a5%5Cud83d%5Cudc97%5Cuc2a4%5Cud30c%5Cuc624%20SPAO%20%5Cubcf4%5Cub4e4%5Cubcf4%5Cub4e4%20%5Cud6c4%5Cub9ac%5Cuc2a4%20%5Cuc9d1%5Cuc5c5%2010%5Cuceec%5Cub7ec%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FOlvDMHrqRzo%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDE4XzE3MjkyNDgwNjk0NTYyOTltLnBuZw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%203%2C%20%22original_price%22%3A%2029900%2C%20%22price%22%3A%2028800%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "17663829",
                  GOODS_NAME: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
                  MARKET_TYPE: "프리미엄 브랜드",
                  MARKET_SNO: "64739",
                  MARKET_NAME: "제이와이홀딩스",
                  CATEGORY_SNO: "577",
                  CATEGORY_NAME: "플리스",
                  STANDARD_CATEGORY_SNO: "12",
                  STANDARD_CATEGORY_NAME: "플리스",
                  DISCOUNT_RATE: 3,
                  SALES_PRICE: 28800,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "16",
                  REVIEW_COUNT: 938,
                  REVIEW_COUNT_RANGE: "901~950",
                  REVIEW_RATING: 97,
                  LIKES_COUNT: 26603,
                  LIKES_COUNT_RANGE: "26,601~26,650",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: ["BRAND"],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 4,
                  BRAND_SNO: 15609,
                  BRAND_NAME: "스파오",
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 17663829,
                  list_id: "today_recommend",
                  list_index: 4,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING_CHIPS",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/038iy9jUgMA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzU1MWFmYjQyN2I5MzgyZjZlMzc0NWE1YjliMzQzYjdiLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
                  price: "28,800",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "3%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: [
                    {
                      type: "BRAND",
                      name: "브랜드",
                    },
                  ],
                  market_name: "스파오",
                  store_text: "<font color='#6093FC'>브랜드</font> 스파오",
                  nudging_text: "14,020개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 31315514,
                name: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
                market_sno: 370,
                market_name: "블리즈",
                image: "https://d3ha2047wt6x28.cloudfront.net/-zZT6otp0-g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmZGZhNTY4ZGU0NDRmZTYwMmMyMjA3NzZmNTNkYzQxLmdpZg",
                closed_reason: null,
                sell_count: 3450,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
                  market_name: "블리즈",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/E6FCgfqh6As/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk0OTEzNDIwMjA5MjNtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/99tr9Fb97to/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkxODY1MDE1NTM2MTguanBn",
                  discount_rate: 15,
                  original_price: 51400,
                  price: 43700,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 43700,
                discount_rate: 15,
                like: {
                  goods_sno: 31315514,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 5,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/31315514/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "셀럽",
                category_name: "코트",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/31315514/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuadc0%5Cuc5ec%5Cuc6c0%2F%5Cuc544%5Cubc29%5Cud54f%5D%20%5Cud3ec%5Cuadfc%20%5Cud6c4%5Cub4dc%20%5Cuc591%5Cud138%20%5Cub5a1%5Cubcf6%5Cuc774%20%5Cud37c%5Cuc790%5Cucf13%20%5Cuc20f%5Cucf54%5Cud2b8%20%5Cub364%5Cube14%5Cuc810%5Cud37c%22%2C%20%22market_name%22%3A%20%22%5Cube14%5Cub9ac%5Cuc988%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FE6FCgfqh6As%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk0OTEzNDIwMjA5MjNtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2F99tr9Fb97to%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkxODY1MDE1NTM2MTguanBn%22%2C%20%22discount_rate%22%3A%2015%2C%20%22original_price%22%3A%2051400%2C%20%22price%22%3A%2043700%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "31315514",
                  GOODS_NAME: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "370",
                  MARKET_NAME: "블리즈",
                  CATEGORY_SNO: "296",
                  CATEGORY_NAME: "코트",
                  STANDARD_CATEGORY_SNO: "8",
                  STANDARD_CATEGORY_NAME: "코트",
                  DISCOUNT_RATE: 15,
                  SALES_PRICE: 43700,
                  SALES_PRICE_RANGE: "40,001~45,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 13,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 92,
                  LIKES_COUNT: 22038,
                  LIKES_COUNT_RANGE: "22,001~22,050",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 5,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 31315514,
                  list_id: "today_recommend",
                  list_index: 5,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/-zZT6otp0-g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmZGZhNTY4ZGU0NDRmZTYwMmMyMjA3NzZmNTNkYzQxLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
                  price: "43,700",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "15%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "블리즈",
                  store_text: "블리즈",
                  nudging_text: "3,450개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 32378163,
                name: "한겨울까지❄️[밍크기모🖤/숏,미들,롱] 스모어 밍크 기모 허리 밴딩 롱와이드 하이웨스트 트레이닝 와이드 팬츠 키작녀 키큰녀 빅사이즈 융털 융기모 기모바지 롱팬츠",
                market_sno: 23347,
                market_name: "자스민벨",
                image: "https://d3ha2047wt6x28.cloudfront.net/ug4QSgCf23o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2FiOWFjM2EyYWFkNGQ1NjhhM2IyYWRkMzQ4YmMyYWE2LmdpZg",
                closed_reason: null,
                sell_count: 1351,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "한겨울까지❄️[밍크기모🖤/숏,미들,롱] 스모어 밍크 기모 허리 밴딩 롱와이드 하이웨스트 트레이닝 와이드 팬츠 키작녀 키큰녀 빅사이즈 융털 융기모 기모바지 롱팬츠",
                  market_name: "자스민벨",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/5aDUWAFX8rI/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMxXzE3MzAzMzI3OTcyNDE2NDJtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/v-8lxgil7H8/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2ODQ2Nzg5NTA4MzgzMzkuanBn",
                  discount_rate: 17,
                  original_price: 24000,
                  price: 19800,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 19800,
                discount_rate: 17,
                like: {
                  goods_sno: 32378163,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 6,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/32378163/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "셀럽",
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/32378163/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5Cud55c%5Cuaca8%5Cuc6b8%5Cuae4c%5Cuc9c0%5Cu2744%5Cufe0f%5B%5Cubc0d%5Cud06c%5Cuae30%5Cubaa8%5Cud83d%5Cudda4%2F%5Cuc20f%2C%5Cubbf8%5Cub4e4%2C%5Cub871%5D%20%5Cuc2a4%5Cubaa8%5Cuc5b4%20%5Cubc0d%5Cud06c%20%5Cuae30%5Cubaa8%20%5Cud5c8%5Cub9ac%20%5Cubc34%5Cub529%20%5Cub871%5Cuc640%5Cuc774%5Cub4dc%20%5Cud558%5Cuc774%5Cuc6e8%5Cuc2a4%5Cud2b8%20%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%20%5Cuc640%5Cuc774%5Cub4dc%20%5Cud32c%5Cuce20%20%5Cud0a4%5Cuc791%5Cub140%20%5Cud0a4%5Cud070%5Cub140%20%5Cube45%5Cuc0ac%5Cuc774%5Cuc988%20%5Cuc735%5Cud138%20%5Cuc735%5Cuae30%5Cubaa8%20%5Cuae30%5Cubaa8%5Cubc14%5Cuc9c0%20%5Cub871%5Cud32c%5Cuce20%22%2C%20%22market_name%22%3A%20%22%5Cuc790%5Cuc2a4%5Cubbfc%5Cubca8%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2F5aDUWAFX8rI%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMxXzE3MzAzMzI3OTcyNDE2NDJtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2Fv-8lxgil7H8%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2ODQ2Nzg5NTA4MzgzMzkuanBn%22%2C%20%22discount_rate%22%3A%2017%2C%20%22original_price%22%3A%2024000%2C%20%22price%22%3A%2019800%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "32378163",
                  GOODS_NAME: "한겨울까지❄️[밍크기모🖤/숏,미들,롱] 스모어 밍크 기모 허리 밴딩 롱와이드 하이웨스트 트레이닝 와이드 팬츠 키작녀 키큰녀 빅사이즈 융털 융기모 기모바지 롱팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "23347",
                  MARKET_NAME: "자스민벨",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 17,
                  SALES_PRICE: 19800,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 13,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 3515,
                  LIKES_COUNT_RANGE: "3,501~3,550",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 6,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 32378163,
                  list_id: "today_recommend",
                  list_index: 6,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/ug4QSgCf23o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2FiOWFjM2EyYWFkNGQ1NjhhM2IyYWRkMzQ4YmMyYWE2LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "한겨울까지❄️[밍크기모🖤/숏,미들,롱] 스모어 밍크 기모 허리 밴딩 롱와이드 하이웨스트 트레이닝 와이드 팬츠 키작녀 키큰녀 빅사이즈 융털 융기모 기모바지 롱팬츠",
                  price: "19,800",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "17%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "자스민벨",
                  store_text: "자스민벨",
                  nudging_text: "1,351개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 31596925,
                name: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
                market_sno: 14929,
                market_name: "리즈리버",
                image: "https://d3ha2047wt6x28.cloudfront.net/OMT_zzSeCKg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMwYWRmOThjMGM4YjA5OTVlYzllZGVkOTNlZDAyYjk2LmdpZg",
                closed_reason: null,
                sell_count: 2673,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
                  market_name: "리즈리버",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/Z7r5fYV_UdU/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI0XzE3Mjk3NDY1OTU1ODMyNDdtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/RI8K48NgO_I/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjM2MjcxMDE4OTM4ODMuanBn",
                  discount_rate: 26,
                  original_price: 33000,
                  price: 24410,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 24410,
                discount_rate: 26,
                like: {
                  goods_sno: 31596925,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 7,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/31596925/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "셀럽",
                category_name: "니트",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/31596925/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%2AV%5Cub125%5Cuc624%5Cud508%21%5Cuadf9%5Cucc2c%5Cud54f%5Cud83d%5Cudc30%5Cud83e%5Cuddf6%5D%5Cubcf4%5Cuce74%5Cuc2dc%20%5Cubbf9%5Cuc2a4%20%5Cub2c8%5Cud2b8%20%3A%20mix%20color%20knit%20-%209%20color%22%2C%20%22market_name%22%3A%20%22%5Cub9ac%5Cuc988%5Cub9ac%5Cubc84%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FZ7r5fYV_UdU%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI0XzE3Mjk3NDY1OTU1ODMyNDdtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FRI8K48NgO_I%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjM2MjcxMDE4OTM4ODMuanBn%22%2C%20%22discount_rate%22%3A%2026%2C%20%22original_price%22%3A%2033000%2C%20%22price%22%3A%2024410%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "31596925",
                  GOODS_NAME: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14929",
                  MARKET_NAME: "리즈리버",
                  CATEGORY_SNO: "299",
                  CATEGORY_NAME: "니트",
                  STANDARD_CATEGORY_SNO: "19",
                  STANDARD_CATEGORY_NAME: "니트",
                  DISCOUNT_RATE: 26,
                  SALES_PRICE: 24410,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 42,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 83,
                  LIKES_COUNT: 12990,
                  LIKES_COUNT_RANGE: "12,951~13,000",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 7,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 31596925,
                  list_id: "today_recommend",
                  list_index: 7,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/OMT_zzSeCKg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMwYWRmOThjMGM4YjA5OTVlYzllZGVkOTNlZDAyYjk2LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
                  price: "24,410",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "26%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "리즈리버",
                  store_text: "리즈리버",
                  nudging_text: "2,673개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 33198315,
                name: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
                market_sno: 7539,
                market_name: "홀리",
                image: "https://d3ha2047wt6x28.cloudfront.net/F9o_KRVKRc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQ0M2YwMGY3MDM5YzY2YzA1NThmOWVkZGJlMDQ2NjE3LmdpZg",
                closed_reason: null,
                sell_count: 575,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
                  market_name: "홀리",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/RZ-WY0XiH4Q/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTA2XzE3MzA4NzQ4NTIwOTQ3OTBtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/pcfpQ83n63E/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzgwNzM2NzQzOTg1MDcucG5n",
                  discount_rate: 52,
                  original_price: 70000,
                  price: 33200,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 33200,
                discount_rate: 52,
                like: {
                  goods_sno: 33198315,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 8,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/33198315/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "셀럽",
                category_name: "투피스",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/33198315/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%282size%2F%5Cuae30%5Cubcf8%2C%5Cub871%29%5B%5Cubd80%5Cud568X%5Cud5c8%5Cuc587%5Cuace8%5Cub113%5Cud83e%5Cudd0d%5D%20made%20%5Cud3ec%5Cud150%20%5Cub2c8%5Cud2b8%20%5Cuae30%5Cubaa8%20%5Cuc2ac%5Cub9bc%5Cud54f%20%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%5Cuc138%5Cud2b8%20%5Cuae30%5Cubaa8%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%20%5Cub2c8%5Cud2b8%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%20%5Cud640%5Cub9ac%5Cuc81c%5Cuc791%22%2C%20%22market_name%22%3A%20%22%5Cud640%5Cub9ac%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FRZ-WY0XiH4Q%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTA2XzE3MzA4NzQ4NTIwOTQ3OTBtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FpcfpQ83n63E%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzgwNzM2NzQzOTg1MDcucG5n%22%2C%20%22discount_rate%22%3A%2052%2C%20%22original_price%22%3A%2070000%2C%20%22price%22%3A%2033200%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "33198315",
                  GOODS_NAME: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "7539",
                  MARKET_NAME: "홀리",
                  CATEGORY_SNO: "208",
                  CATEGORY_NAME: "투피스",
                  STANDARD_CATEGORY_SNO: "33",
                  STANDARD_CATEGORY_NAME: "투피스",
                  DISCOUNT_RATE: 52,
                  SALES_PRICE: 33200,
                  SALES_PRICE_RANGE: "30,001~35,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 1,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 917,
                  LIKES_COUNT_RANGE: "901~950",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 8,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 33198315,
                  list_id: "today_recommend",
                  list_index: 8,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/F9o_KRVKRc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQ0M2YwMGY3MDM5YzY2YzA1NThmOWVkZGJlMDQ2NjE3LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
                  price: "33,200",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "52%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "홀리",
                  store_text: "홀리",
                  nudging_text: "575개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 32375640,
                name: "[의약외품] 셀프 치아미백제 1개",
                market_sno: 76585,
                market_name: "구스투스",
                image: "https://d3ha2047wt6x28.cloudfront.net/vdBXPll2T0o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk3ZmZiYTk4NThjN2FlOTZkZGI1MzQ2NTEyYjczMDI4LmpwZw",
                closed_reason: null,
                sell_count: 1866,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "[의약외품] 셀프 치아미백제 1개",
                  market_name: null,
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/weWv8GfDFzI/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNzQ4MjgzOTAwNTNtLmpwZw",
                  market_image: null,
                  discount_rate: 27,
                  original_price: 22000,
                  price: 15900,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 15900,
                discount_rate: 27,
                like: {
                  goods_sno: 32375640,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 9,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/32375640/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "뷰티",
                category_name: "기타메이크업 소품",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/32375640/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc758%5Cuc57d%5Cuc678%5Cud488%5D%20%5Cuc140%5Cud504%20%5Cuce58%5Cuc544%5Cubbf8%5Cubc31%5Cuc81c%201%5Cuac1c%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FweWv8GfDFzI%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNzQ4MjgzOTAwNTNtLmpwZw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%2027%2C%20%22original_price%22%3A%2022000%2C%20%22price%22%3A%2015900%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "32375640",
                  GOODS_NAME: "[의약외품] 셀프 치아미백제 1개",
                  MARKET_TYPE: "뷰티",
                  MARKET_SNO: "76585",
                  MARKET_NAME: "구스투스",
                  CATEGORY_SNO: "643",
                  CATEGORY_NAME: "기타메이크업 소품",
                  STANDARD_CATEGORY_SNO: "454",
                  STANDARD_CATEGORY_NAME: "기타메이크업 소품",
                  DISCOUNT_RATE: 27,
                  SALES_PRICE: 15900,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "3",
                  REVIEW_COUNT: 11,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 10005,
                  LIKES_COUNT_RANGE: "10,001~10,050",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 9,
                  BRAND_SNO: 15701,
                  BRAND_NAME: "구스투스",
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 32375640,
                  list_id: "today_recommend",
                  list_index: 9,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/vdBXPll2T0o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk3ZmZiYTk4NThjN2FlOTZkZGI1MzQ2NTEyYjczMDI4LmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[의약외품] 셀프 치아미백제 1개",
                  price: "15,900",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "27%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "구스투스",
                  store_text: "구스투스",
                  nudging_text: "1,866개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 32460358,
                name: "[핏보장🤎] 아센 비조 사이드 스냅 롱 와이드 팬츠 (5color)",
                market_sno: 10085,
                market_name: "애니원모어",
                image: "https://d3ha2047wt6x28.cloudfront.net/R25H3ltCs_o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2VhNzk4ZWI5YzQyNDhhZmUwNDA4ZDAzN2JhZTE2MjNhLmdpZg",
                closed_reason: null,
                sell_count: 2671,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "[핏보장🤎] 아센 비조 사이드 스냅 롱 와이드 팬츠 (5color)",
                  market_name: "애니원모어",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/LAaj2amD-pE/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMxXzE3MzAzNjU1MjQ0MDc4NTZtLmpwZw",
                  market_image: "https://d3ha2047wt6x28.cloudfront.net/-R5Lje6YXLU/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDE4Nzg4MDc3NDgucG5n",
                  discount_rate: 41,
                  original_price: 25900,
                  price: 15200,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 15200,
                discount_rate: 41,
                like: {
                  goods_sno: 32460358,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 10,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/32460358/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "쇼핑몰",
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/32460358/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cud54f%5Cubcf4%5Cuc7a5%5Cud83e%5Cudd0e%5D%20%5Cuc544%5Cuc13c%20%5Cube44%5Cuc870%20%5Cuc0ac%5Cuc774%5Cub4dc%20%5Cuc2a4%5Cub0c5%20%5Cub871%20%5Cuc640%5Cuc774%5Cub4dc%20%5Cud32c%5Cuce20%20%285color%29%22%2C%20%22market_name%22%3A%20%22%5Cuc560%5Cub2c8%5Cuc6d0%5Cubaa8%5Cuc5b4%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FLAaj2amD-pE%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMxXzE3MzAzNjU1MjQ0MDc4NTZtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2F-R5Lje6YXLU%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDE4Nzg4MDc3NDgucG5n%22%2C%20%22discount_rate%22%3A%2041%2C%20%22original_price%22%3A%2025900%2C%20%22price%22%3A%2015200%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "32460358",
                  GOODS_NAME: "[핏보장🤎] 아센 비조 사이드 스냅 롱 와이드 팬츠 (5color)",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "10085",
                  MARKET_NAME: "애니원모어",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 41,
                  SALES_PRICE: 15200,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 0,
                  REVIEW_COUNT_RANGE: "0",
                  REVIEW_RATING: 0,
                  LIKES_COUNT: 7284,
                  LIKES_COUNT_RANGE: "7,251~7,300",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: [],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 10,
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 32460358,
                  list_id: "today_recommend",
                  list_index: 10,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/R25H3ltCs_o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2VhNzk4ZWI5YzQyNDhhZmUwNDA4ZDAzN2JhZTE2MjNhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[핏보장🤎] 아센 비조 사이드 스냅 롱 와이드 팬츠 (5color)",
                  price: "15,200",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "41%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: null,
                  market_name: "애니원모어",
                  store_text: "애니원모어",
                  nudging_text: "2,671개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 29194549,
                name: "호주어그 DK 바이올렛 시어링 어그슬리퍼,플랫폼슬리퍼  dk143",
                market_sno: 53695,
                market_name: "오즈웨어",
                image: "https://d3ha2047wt6x28.cloudfront.net/zOSOo_9Fjac/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzAxYjdlOWM0M2RkZGFjZjU2MTQ0YzYxNTIyNDkzMTM5LmpwZw",
                closed_reason: null,
                sell_count: 1806,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "호주어그 DK 바이올렛 시어링 어그슬리퍼,플랫폼슬리퍼  dk143",
                  market_name: null,
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/E7CjOsUoLyo/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQwOTMwXzE3Mjc3MDMzMjU2ODE5MzBtLkpQRw",
                  market_image: null,
                  discount_rate: 60,
                  original_price: 164000,
                  price: 64000,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 64000,
                discount_rate: 60,
                like: {
                  goods_sno: 29194549,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 11,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/29194549/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "프리미엄 브랜드",
                category_name: "슬리퍼/쪼리",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/29194549/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5Cud638%5Cuc8fc%5Cuc5b4%5Cuadf8%20DK%20%5Cubc14%5Cuc774%5Cuc62c%5Cub81b%20%5Cuc2dc%5Cuc5b4%5Cub9c1%20%5Cuc5b4%5Cuadf8%5Cuc2ac%5Cub9ac%5Cud37c%2C%5Cud50c%5Cub7ab%5Cud3fc%5Cuc2ac%5Cub9ac%5Cud37c%20%20dk143%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FE7CjOsUoLyo%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQwOTMwXzE3Mjc3MDMzMjU2ODE5MzBtLkpQRw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%2060%2C%20%22original_price%22%3A%20164000%2C%20%22price%22%3A%2064000%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "29194549",
                  GOODS_NAME: "호주어그 DK 바이올렛 시어링 어그슬리퍼,플랫폼슬리퍼  dk143",
                  MARKET_TYPE: "프리미엄 브랜드",
                  MARKET_SNO: "53695",
                  MARKET_NAME: "오즈웨어",
                  CATEGORY_SNO: "492",
                  CATEGORY_NAME: "슬리퍼/쪼리",
                  STANDARD_CATEGORY_SNO: "108",
                  STANDARD_CATEGORY_NAME: "슬리퍼",
                  DISCOUNT_RATE: 60,
                  SALES_PRICE: 64000,
                  SALES_PRICE_RANGE: "60,001~65,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "16",
                  REVIEW_COUNT: 73,
                  REVIEW_COUNT_RANGE: "51~100",
                  REVIEW_RATING: 95,
                  LIKES_COUNT: 3312,
                  LIKES_COUNT_RANGE: "3,301~3,350",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: ["BRAND"],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 11,
                  BRAND_SNO: 2053,
                  BRAND_NAME: "어그",
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 29194549,
                  list_id: "today_recommend",
                  list_index: 11,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING_CHIPS",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/zOSOo_9Fjac/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzAxYjdlOWM0M2RkZGFjZjU2MTQ0YzYxNTIyNDkzMTM5LmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "호주어그 DK 바이올렛 시어링 어그슬리퍼,플랫폼슬리퍼  dk143",
                  price: "64,000",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "60%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: [
                    {
                      type: "BRAND",
                      name: "브랜드",
                    },
                  ],
                  market_name: "어그",
                  store_text: "<font color='#6093FC'>브랜드</font> 어그",
                  nudging_text: "1,806개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 12017074,
                name: "[시즌오프세일]오즈웨어 코케트 어그슬리퍼 퍼스트랩 ob114rbf",
                market_sno: 53695,
                market_name: "오즈웨어",
                image: "https://d3ha2047wt6x28.cloudfront.net/hDMJWDaMMcE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk2OTA3MjE0NDNlZGQwMWFhNWIwYzNhYzdjMzIwNzdiLmdpZg",
                closed_reason: null,
                sell_count: 10993,
                delivery_type: "standard",
                ranking: null,
                available_only_new_member: false,
                first_page_rendering: {
                  goods_name: "[시즌오프세일]오즈웨어 코케트 어그슬리퍼 퍼스트랩 ob114rbf",
                  market_name: null,
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/Zy4Qy0gO76U/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjMxMTE1XzE3MDAwNDMyODAzMzA5OTBtLkpQRw",
                  market_image: null,
                  discount_rate: 59,
                  original_price: 158900,
                  price: 64900,
                },
                is_premium_hotdeal: false,
                is_hotdeal: false,
                is_new: false,
                price: 64900,
                discount_rate: 59,
                like: {
                  goods_sno: 12017074,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 12,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/12017074/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                market_type: "프리미엄 브랜드",
                category_name: "워커/부츠",
                feedback_type: "contain_icon",
                remote_deeplink:
                  "ably://goods/12017074/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc2dc%5Cuc98c%5Cuc624%5Cud504%5Cuc138%5Cuc77c%5D%5Cuc624%5Cuc988%5Cuc6e8%5Cuc5b4%20%5Cucf54%5Cucf00%5Cud2b8%20%5Cuc5b4%5Cuadf8%5Cuc2ac%5Cub9ac%5Cud37c%20%5Cud37c%5Cuc2a4%5Cud2b8%5Cub7a9%20ob114rbf%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FZy4Qy0gO76U%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjMxMTE1XzE3MDAwNDMyODAzMzA5OTBtLkpQRw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%2059%2C%20%22original_price%22%3A%20158900%2C%20%22price%22%3A%2064900%7D",
              },
              logging: {
                analytics: {
                  GOODS_SNO: "12017074",
                  GOODS_NAME: "[시즌오프세일]오즈웨어 코케트 어그슬리퍼 퍼스트랩 ob114rbf",
                  MARKET_TYPE: "프리미엄 브랜드",
                  MARKET_SNO: "53695",
                  MARKET_NAME: "오즈웨어",
                  CATEGORY_SNO: "493",
                  CATEGORY_NAME: "워커/부츠",
                  STANDARD_CATEGORY_SNO: "111",
                  STANDARD_CATEGORY_NAME: "부츠",
                  DISCOUNT_RATE: 59,
                  SALES_PRICE: 64900,
                  SALES_PRICE_RANGE: "60,001~65,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "16",
                  REVIEW_COUNT: 1271,
                  REVIEW_COUNT_RANGE: "1,251~1,300",
                  REVIEW_RATING: 98,
                  LIKES_COUNT: 30526,
                  LIKES_COUNT_RANGE: "30,501~30,550",
                  DELIVERY_SCORE: null,
                  PROMOTION_TAG: ["BRAND"],
                  UPCOMMING_SOLDOUT: "",
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 12,
                  BRAND_SNO: 2053,
                  BRAND_NAME: "어그",
                  CARD_TYPE: "GOODS_CARD",
                },
                inhouse: {
                  goods_sno: 12017074,
                  list_id: "today_recommend",
                  list_index: 12,
                  schema_name: "Goods",
                  pool: "best",
                },
              },
              render: {
                type: "MARKET_NUDGING_CHIPS",
                contents: ["PRICE", "NAME", "MARKET", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/hDMJWDaMMcE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk2OTA3MjE0NDNlZGQwMWFhNWIwYzNhYzdjMzIwNzdiLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[시즌오프세일]오즈웨어 코케트 어그슬리퍼 퍼스트랩 ob114rbf",
                  price: "64,900",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "59%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  chips: [
                    {
                      type: "BRAND",
                      name: "브랜드",
                    },
                  ],
                  market_name: "어그",
                  store_text: "<font color='#6093FC'>브랜드</font> 어그",
                  nudging_text: "10,993개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
        ],
        footer: null,
      },
    },
  ],
  next_token: "eyJsaSI6IDIsICJuIjogImV5SnNZWE4wWDJsdVpHVjRJam9nTVROOSJ9",
  view_event_channels: ["firebase", "amplitude", "ablylog", "facebook", "appsflyer"],
};
